# Generated by Django 5.2.9 on 2025-12-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("date_time", models.DateTimeField()),
                (
                    "venue_image",
                    models.ImageField(blank=True, null=True, upload_to="venue_maps/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("discount_percentage", models.PositiveIntegerField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_label", models.CharField(max_length=10)),
                ("seat_number", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("BOOKED", "Booked"),
                            ("RESERVED", "Reserved"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tier", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "x_coordinate",
                    models.FloatField(
                        help_text="X coordinate on the venue map (percentage or pixels)"
                    ),
                ),
                (
                    "y_coordinate",
                    models.FloatField(
                        help_text="Y coordinate on the venue map (percentage or pixels)"
                    ),
                ),
            ],
        ),
    ]
